apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inference-service
  namespace: ai-inference
  labels:
    # 이름 확인 후 변경
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: inference-service
  namespaceSelector:
    matchNames:
      - ai-inference
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
